<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.7" />
    <PackageReference Include="Microsoft.IdentityModel.Logging" Version="8.17.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MPL.X4.Services\MPL.X4.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="MapIcons.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MapIcons.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="MapIcons.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>MapIcons.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>